# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - windows
      - darwin
    flags:
      - -trimpath

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - name: "{{ .ProjectName }}"
    homepage: https://github.com/sosheskaz/healthchecksio-cli
    description: "A simple CLI for healthchecks.io."
    repository:
      owner: sosheskaz
      name: homebrew-tap
    completions:
      bash: completions/bash_completion.bash
      zsh: completions/zsh_completion.zsh
      fish: completions/fish_completion.fish

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

kos:
  - repositories: [ghcr.io/sosheskaz/healthchecksio-cli]
    tags:
      - "{{.Version}}"
      - "{{.Major}}"
      - "{{.Major}}.{{.Minor}}"
      - latest
    sbom: none
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/riscv64
