[tools]
go = "1.26.4"
golangci-lint = "2.12.2"
goreleaser = "2.16.0"
ko = "0.18.1"

lefthook = "2.1.9"
"aqua:rhysd/actionlint" = "1.7.12"

node = "24.16.0"
"npm:renovate" = "43.210.2"
"npm:release-please" = "17.7.0"
