on:
  push:
    branches:
      - main
      - update-builds
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          install_args: 'node npm:release-please'
      - id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
  goreleaser:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release_tag: ${{ needs.release-please.outputs.tag_name }}
